const errorCodes = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  PRISMA_UNIQUE_CONSTRAINT_FAILED: "PRISMA_UNIQUE_CONSTRAINT_FAILED",
  PRISMA_RECORD_NOT_FOUND: "PRISMA_RECORD_NOT_FOUND",
  PRISMA_UNKNOWN_ERROR: "PRISMA_UNKNOWN_ERROR",
};

export type ErrorCode = keyof typeof errorCodes;

export default errorCodes;
