import { errorCodes as fastifyErrorCodes } from "fastify";

const errorCodes = {
  ...fastifyErrorCodes,
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  PRISMA_UNIQUE_CONSTRAINT_FAILED: "PRISMA_UNIQUE_CONSTRAINT_FAILED",
  PRISMA_FOREIGN_KEY_CONSTRAINT: "PRISMA_FOREIGN_KEY_CONSTRAINT",
  PRISMA_RECORD_NOT_FOUND: "PRISMA_RECORD_NOT_FOUND",
  PRISMA_UNKNOWN_ERROR: "PRISMA_UNKNOWN_ERROR",
} as const;

export type ErrorCode = keyof typeof errorCodes;

export default errorCodes;
